
# Use a imagem oficial do Node.js com Alpine (versão LTS recomendada)
FROM node:18-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de definição de dependências
COPY package.json package-lock.json ./

RUN npm ci --only=production

# Copia o restante dos arquivos do projeto
COPY . .

# Cria o diretório de logs se não existir
RUN mkdir -p ./logs/sql
RUN touch " " >> ./logs/sql.log.txt

# Comando para iniciar o consumer
CMD ["node", "consumer.js"]