
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"          # Porta AMQP
      - "15672:15672"        # Interface web
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network
    healthcheck:  # Adicione esta seção
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  consumer:
    build: ./
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./consumer/logs:/app/logs
    networks:
      - app_network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  app_network:
    driver: bridge